[supervisord]
nodaemon=true

[program:daphne]
command=daphne -b 127.0.0.1 -p 8000 nebiralserpback.asgi:application
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

