# Generated by Django 6.1 on 2026-08-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoseo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords',
        ),
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
