# Generated by Django 6.1 on 2026-08-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoseo', '0002_remove_page_analysis_remove_page_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alt',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
