# Generated by Django 6.1 on 2026-08-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoseo', '0003_page_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_analyz', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
